// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGaqje6Q4CutmqZ0k33yGXeMyYIzT_EwI',
    appId: '1:832788585740:web:b6b6c809b45a31a67afd29',
    messagingSenderId: '832788585740',
    projectId: 'chat-app-c1ca5',
    authDomain: 'chat-app-c1ca5.firebaseapp.com',
    storageBucket: 'chat-app-c1ca5.appspot.com',
    measurementId: 'G-74ZRHVTZ6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoHp0aNGUCGXOJNwD4hNXKiWIrXBaXsMQ',
    appId: '1:832788585740:android:6581b75313544c887afd29',
    messagingSenderId: '832788585740',
    projectId: 'chat-app-c1ca5',
    storageBucket: 'chat-app-c1ca5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsvsujV4FpxOEPQ9JQeRtijiFuKdXYKcM',
    appId: '1:832788585740:ios:85264a3e8991052b7afd29',
    messagingSenderId: '832788585740',
    projectId: 'chat-app-c1ca5',
    storageBucket: 'chat-app-c1ca5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsvsujV4FpxOEPQ9JQeRtijiFuKdXYKcM',
    appId: '1:832788585740:ios:7eb70f29892e6e557afd29',
    messagingSenderId: '832788585740',
    projectId: 'chat-app-c1ca5',
    storageBucket: 'chat-app-c1ca5.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
